apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/app-secrets.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      # initContainers:
      # - name: init-smart-intersection-ri-web
      #   image: busybox
      #   command: ['sh', '-c', '
      #     if [ -f /data/secrets.py ]; then
      #       echo "File exists: /data/secrets.py";
      #     else
      #       echo "File does NOT exist: /data/secrets.py";
      #     fi &&
      #     until [ -f /data/.done ]; do
      #       echo "Waiting for .done ...";
      #       sleep 5;
      #     done &&
      #     ls /tmp &&
      #     echo "Files copied to /tmp";
      #   ']
      #   volumeMounts:
      #   - name: smart-intersection-ri-web-data
      #     mountPath: /data
      containers:
      - name: web
        image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: http_proxy
          value: {{ .Values.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.https_proxy | quote }}
        - name: no_proxy
          value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-intersection-broker,smart-intersection-dlstreamer-pipeline-server,smart-intersection-grafana,smart-intersection-nodered,smart-intersection-pgserver,smart-intersection-scene,smart-intersection-web"
        - name: DBROOT
          value: /workspace
        - name: RUNSECRETS
          value: /run/secrets
        - name: SSCAPEDIR
          value: /home/scenescape/SceneScape
        volumeMounts:
        - name: pgserver-media
          mountPath: /workspace/media
        - name: secrets
          mountPath: /tmp/secrets
        - name: smart-intersection-ri-web-data
          mountPath: /data
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true
        command: ["/bin/bash", "-e", "-c"]
        args:
        - >
          {{- tpl (include "web.startup-script" .) . | nindent 10 }}
      volumes:
      - name: pgserver-media
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-media
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ .Release.Name }}-mqtt-auth-secrets
          - secret:
              name: {{ .Release.Name }}-django-secrets
          - secret:
              name: {{ .Release.Name }}-web-tls
              items:
              - key: tls.crt
                path: scenescape-web.crt
              - key: tls.key
                path: scenescape-web.key
          - secret:
              name: {{ .Release.Name }}-ca-secret
              items:
              - key: tls.crt
                path: scenescape-ca.pem
      - name: {{ .Release.Name }}-ri-web-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-ri-pvc
