apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/app-secrets.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: download-example-db
        image: {{ .Values.images.busybox.repository }}:{{ .Values.images.busybox.tag }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash" ,"-c"]
        args:
        - |
          {{ include "web.startup-script" . | indent 10 }}
        env:
        - name: http_proxy
          value: {{ .Values.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.https_proxy | quote }}
        - name: no_proxy
          value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-intersection-broker,smart-intersection-dlstreamer-pipeline-server,smart-intersection-grafana,smart-intersection-nodered,smart-intersection-pgserver,smart-intersection-scene,smart-intersection-web"
        volumeMounts:
        - name: {{ .Release.Name }}-example-db
          mountPath: /data
      containers:
      - name: web
        image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: http_proxy
          value: {{ .Values.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.https_proxy | quote }}
        - name: no_proxy
          value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-intersection-broker,smart-intersection-dlstreamer-pipeline-server,smart-intersection-grafana,smart-intersection-nodered,smart-intersection-pgserver,smart-intersection-scene,smart-intersection-web"
        - name: DBROOT
          value: /workspace
        - name: MODEL_CONFIGS_FOLDER
            value: /home/scenescape/SceneScape/models/models/model_configs
        - name: SUPASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-supass-secret
              key: supass
        - name: EXAMPLEDB
            value: /home/scenescape/SceneScape/example_db/smart-intersection-ri.tar.bz2
        volumeMounts:
        - name: pgserver-media
          mountPath: /workspace/media
        - name: secrets
          mountPath: /tmp/secrets
        - name: smart-intersection-ri-web-data
          mountPath: /data
        - name: {{ .Release.Name }}-example-db
          mountPath: /home/scenescape/SceneScape/example_db
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true
        args:
        - webserver
        - --dbhost
        - pgserver.{{ .Release.Namespace }}.svc.cluster.local
        - --dbtype
        - postgres
        - --dbport
        - "5432"
        - --broker
        - broker.{{ .Release.Namespace }}.svc.cluster.local
        - --brokerauth
        - /run/secrets/browser.auth
        - --brokerrootcert
        - /run/secrets/certs/scenescape-ca.pem
      volumes:
      - name: pgserver-media
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-media
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ .Release.Name }}-mqtt-auth-secrets
          - secret:
              name: {{ .Release.Name }}-django-secrets
          - secret:
              name: {{ .Release.Name }}-web-tls
              items:
              - key: tls.crt
                path: scenescape-web.crt
              - key: tls.key
                path: scenescape-web.key
          - secret:
              name: {{ .Release.Name }}-ca-secret
              items:
              - key: tls.crt
                path: scenescape-ca.pem
      - name: {{ .Release.Name }}-ri-web-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-ri-pvc
      - name: {{ .Release.Name }}-example-db
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-example-db
