---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-influxdb-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  influxdb2-admin-username: {{ "admin" | b64enc }}
  influxdb2-admin-password: {{ randAlphaNum 16 | b64enc }}
  influxdb2-admin-token: {{ randAlphaNum 32 | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secrets.py: |-
    {{ include "secrets-py" . | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mqtt-auth-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  controller.auth: {{ printf "{\"user\": \"scenectrl\", \"password\": \"%s\"}" (randAlphaNum 16) | b64enc }}
  browser.auth: {{ printf "{\"user\": \"webuser\", \"password\": \"%s\"}" (randAlphaNum 16) | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-supass-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  supass: {{ include "supass" . | b64enc }}
