apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scene
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-scene
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-scene
    spec:
      initContainers:
      - name: wait-for-web-initcontainer
        image: {{ .Values.images.busybox.repository }}:{{ .Values.images.busybox.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["/bin/sh", "-c", "until wget -q --spider http://{{ .Release.Name }}-web; do sleep 1; done"]
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
      containers:
      - name: scene
        image: {{ .Values.scene.repository }}:{{ .Values.scene.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: http_proxy
            value: {{ .Values.http_proxy | quote }}
          - name: https_proxy
            value: {{ .Values.https_proxy | quote }}
          - name: no_proxy
            value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-intersection-broker,smart-intersection-dlstreamer-pipeline-server,smart-intersection-grafana,smart-intersection-nodered,smart-intersection-pgserver,smart-intersection-scene,smart-intersection-web"
        command: ["/bin/bash", "-e", "-c"]
        args:
        - >
          {{- tpl (include "scene.startup-script" .) . | nindent 10 }}
        volumeMounts:
        - name: pgserver-media
          mountPath: /home/scenescape/SceneScape/media
        - name: tracker-config
          mountPath: /home/scenescape/SceneScape/tracker-config.json
          subPath: tracker-config.json
        - mountPath: /tmp/secrets_
          name: secrets
          readOnly: true
        - name: scene-secrets-data
          mountPath: /data
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
        env:
        - name: CONTROLLER_AUTH
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mqtt-auth-secrets
              key: controller.auth
      volumes:
      - name: pgserver-media
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-media
      - name: tracker-config
        configMap:
          name: {{ .Release.Name }}-scene-config
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ .Release.Name }}-django-secrets
          - secret:
              name: {{ .Release.Name }}-mqtt-auth-secrets
          - secret:
              name: {{ .Release.Name }}-ca-secret
              items:
              - key: tls.crt
                path: scenescape-ca.pem
      - name: scene-secrets-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-scene-secrets-pvc
