apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-pgserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgserver
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/app-secrets.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: init-smart-intersection-ri
        image: "{{ .Values.images.alpine.repository }}:{{ .Values.images.alpine.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: http_proxy
            value: {{ .Values.http_proxy | quote }}
          - name: https_proxy
            value: {{ .Values.https_proxy | quote }}
          - name: no_proxy
            value: {{ .Values.no_proxy | quote }}
        command:
        - /bin/sh
        - -c
        - |
          {{- tpl (include "pgserver.init-script" .) . | nindent 10 }}
        volumeMounts:
        - name: smart-intersection-ri-data
          mountPath: /data
      containers:
      - name: pgserver
        image: {{ .Values.pgserver.repository }}:{{ .Values.pgserver.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: http_proxy
          value: {{ .Values.http_proxy | quote }}
        - name: https_proxy
          value: {{ .Values.https_proxy | quote }}
        - name: no_proxy
          value: "{{ .Values.no_proxy }},influxdb2, ntpserv,smart-intersection-broker,smart-intersection-dlstreamer-pipeline-server,smart-intersection-grafana,smart-intersection-nodered,smart-intersection-pgserver,smart-intersection-scene,smart-intersection-web"
        - name: DBROOT
          value: /workspace
        - name: EXAMPLEDB
          value: smart-intersection-ri.tar.bz2
        volumeMounts:
        - name: pgserver-db
          mountPath: /workspace/db
        - name: pgserver-migrations
          mountPath: /workspace/migrations
        - name: pgserver-media
          mountPath: /workspace/media
        - name: pgserver-config
          mountPath: /tmp
        - name: secrets
          mountPath: /tmp/secrets  # Mount secrets in /tmp/secrets
        - name: smart-intersection-ri-data
          mountPath: /data
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true
        command: ["/bin/bash", "-e", "-c"]
        args:
        - >
          sed -i 's+RUNSECRETS=/run/secrets+RUNSECRETS=/tmp/secrets+g' /usr/local/bin/scenescape-init &&
          cp /data/smart-intersection-ri.tar.bz2 /home/scenescape/SceneScape/smart-intersection-ri.tar.bz2 &&
          cp /tmp/secrets/secrets.py /home/scenescape/SceneScape/manager/secrets.py &&
          cp /tmp/user_access_config.json /home/scenescape/SceneScape/user_access_config.json &&
          chown -R scenescape:scenescape /workspace &&
          sed -i 's+/run/secrets+/tmp/secrets+g' /home/scenescape/SceneScape/manager/settings.py &&
          sed -i '/touch \/tmp\/healthy/d' /usr/local/bin/scenescape-init &&
          SUPASS=$(cat /tmp/secrets/supass) /usr/local/bin/scenescape-init database --preloadexample
      volumes:
      - name: pgserver-db
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-db
      - name: pgserver-migrations
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-migrations
      - name: pgserver-media
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pgserver-media
      - name: pgserver-config
        configMap:
          name: {{ .Release.Name }}-pgserver-config
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ .Release.Name }}-mqtt-auth-secrets
          - secret:
              name: {{ .Release.Name }}-django-secrets
          - secret:
              name: {{ .Release.Name }}-supass-secret
      - name: smart-intersection-ri-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-ri-pvc
