# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:

permissions:
  contents: read

env:
  COMPONENT_NAME: its-planner

jobs:
  dummy:
    name: '[${{ env.COMPONENT_NAME }}] Dummy job'
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "This is a placeholder"
